name: calendar_timeline
description: A horizontal date picker that takes up little screen space, so we
  can always have it visible, and that facilitates use with one hand.
version: 1.1.6
homepage: https://github.com/ikicodedev/calendar_timeline

environment:
  sdk: '>=3.10.9 <4.0.0'
  flutter: '>=3.38.10'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=3.1.0 <5.0.0"
